# Site settings
title: Start Jekyll
email: sean.keeley1@gmail.com
description: A simple Jekyll static blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: s3ankeeley
github_username:  s3an

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
kramdown:
  input: GFM
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
