# Site settings
title: A place for thoughts
email: sean.keeley1@gmail.com
description: A simple Jekyll static blog as a personal blog
baseurl: "/seansblog" # the subpath of your site, e.g. /blog
url: "http://github.com/s3ankeeley/seansblog" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: s3ankeeley
github_username:  s3ankeeley

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
kramdown:
  input: GFM
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
